### ISSUE TITLE
Add pytest-runner to requirements/build

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/dask-core-feedstock#1]
@jakirkham commented on [Wed Aug 30 2017](https://github.com/conda-forge/dask-feedstock/issues/26)

Next release of `dask` will require that `pytest-runner` be added to `requirements/build` as this was added to `setup_requires` in PR ( https://github.com/dask/dask/pull/2641 ). This issue serves simply as a reminder to make this change.

**Comment by mrocklin** [comment]
Ah, does this mean that the pytest-runner package is now a required
dependency if you want to pip install dask?

**Comment by jakirkham** [comment]
Don't think so. My impression is that `setup_requires` is bypassed by `pip`, but can't find any evidence to back this up. If I try to install `dask` from GitHub with `pip`, it proceeds without issues and does not appear to install `pytest-runner`.

**Comment by jakirkham** [comment]
@nicoddemus, do you know how `pip` handles `pytest-runner` when specified in `setup_requires`?

**Comment by nicoddemus** [comment]
@jakirkham my impression is the same as yours, but I also don't know the details. Tagging @jaraco in case he wants to chime in.

**Comment by jaraco** [comment]
I don't believe pip does or could suppress installation of unsatisfied setup_requires declared in the setup.py, because setup_requires runs very early.

> it proceeds without issues and does not appear to install `pytest-runner`.

My guess is that it's getting downloaded by easy_install during the invocation of setup.py, stored in a .eggs directory in the pip temporary build directory, and then removed after the install is completed. I suggest running with `-vvv` or similar if you're concerned about it appearing as a build dependency. I tried, but didn't know what command to run.

As you can see in the pytest-runner readme, it's already a [published consideration](https://github.com/pytest-dev/pytest-runner#considerations).

> does this mean that the pytest-runner package is now a required dependency if you want to pip install dask?

It depends on how you think about it. It's a setup-time dependency so will be required when setup.py is invoked... so that's during sdist installs (even with pip). But even so, it's a transient dependency. It gets installed only for that invocation. It doesn't become a runtime dependency and is never installed into the target environment. Furthermore, if the project publishes wheels, then it's possible to install from those wheels instead of the sdist and bypass the setup.py invocation altogether. So in many ways, it won't be a required dependency.

**Comment by jakirkham** [comment]
Interesting. Thanks for the info.

**Comment by jcrist** [comment]
The suggestion to add it optionally to `setup_requires` was implemented in https://github.com/dask/dask/pull/2692. I think this can be closed?

**Comment by jakirkham** [comment]
Yes, can be closed. Sorry for not speaking up sooner. Thanks @jcrist.
