### ISSUE TITLE
Dask requires numpy>1.12 and toolz

### ISSUE THREAD

**Issue by carterbox** [conda-forge/dask-core-feedstock#45]
The dask recipe is missing some dependency specifications. For example, if you create the following environment:
```bash
conda create -n dask dask-core numpy=1.12
```
Then then the following import will fail in two ways:
1. The `toolz` package is missing
2. `numpy` should be `>1.12` or else numpy is missing divmod
```
python -c "import dask.array"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chingd/miniconda3/envs/dask/lib/python3.6/site-packages/dask/array/__init__.py", line 26, in <module>
    from .routines import (
  File "/home/chingd/miniconda3/envs/dask/lib/python3.6/site-packages/dask/array/routines.py", line 22, in <module>
    from .ufunc import multiply, sqrt
  File "/home/chingd/miniconda3/envs/dask/lib/python3.6/site-packages/dask/array/ufunc.py", line 367, in <module>
    @copy_docstring(source=np.divmod)
AttributeError: module 'numpy' has no attribute 'divmod'
```

**Comment by carterbox** [comment]
Found this error when fixing: https://github.com/tomopy/tomopy/issues/432

**Comment by jrbourbeau** [comment]
Thanks for raising this @carterbox. The `dask-core` recipe is meant to cover a minimal subset of Dask that only depends on the Python standard library, as some users would like to use this functionality without installing the full set of dependencies needed for the entire Dask package. Dependencies need for things beyond this core functionality, e.g. `dask.array` and `dask.dataframe`, are included in the [`dask` recipe](https://github.com/conda-forge/dask-feedstock), which itself depends on the `dask-core` recipe.

Note that the `dask` recipe includes both `toolz` and `numpy >=1.13.0` as dependencies:

https://github.com/conda-forge/dask-feedstock/blob/edc3083c8c0e7a3ac137cc6f10cea2867f83419c/recipe/meta.yaml#L20-L30

Modifying your example `conda` environment to use the `dask` package, instead of `dask-core`, should fix any import issues with `dask.array`.

**Comment by carterbox** [comment]
Thanks for the response! That probably means my problem is with `scikit-image`.
